### ISSUE TITLE
Error when getting moderate content

### ISSUE THREAD

**Issue by dev-fJ-del** [Blazored/TextEditor#12]
When trying to fetch moderate size data e.g. 3 pages of word document content
`await QuillHtml.GetHTML()`
, following error occur:

> System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'

Update: Looks like when I added an images, await QuillHtml.GetHTML() breaks.

**Comment by ADefWebserver** [comment]
Yes the control only allows you to insert images using the "InsertImage" and that doesn't actually insert-the-image, but, rather inserts a hyperlink to an image.

The reason for this is that it is an unacceptable risk, to me at least, for this control to actually upload images. In my experience, this is where other rich text controls have gone wrong and exposed thousands of websites to being hacked.

If you need to upload images, I have an example project here: [Simple blogging application written in Microsoft Server Side Blazor](https://github.com/ADefWebserver/Blazor-Blogs) .
