### ISSUE TITLE
How to customize enter click event?

### ISSUE THREAD

**Issue by trancongphong** [Blazored/TextEditor#18]
I have a texteditor defined like this:
`BlazoredTextEditor TextEditor { get; set; }`

And the markup:
`<BlazoredTextEditor @ref="@TextEditor">
	<ToolbarContent>
		...
	</ToolbarContent>
	<EditorContent>
		<h4>This Toolbar works with HTML</h4>
		<a href="http://BlazorHelpWebsite.com">
			BlazorHelpWebsite.com
		</a>
	</EditorContent>
</BlazoredTextEditor>`

How can I customize enter click event on EditorContent (ex: submit the content instead of break the new line)

**Comment by ADefWebserver** [comment]
To customize the editor, please see the documentation for the underlying JavaScript Quill.js editor control: https://quilljs.com/docs/quickstart/

**Comment by trancongphong** [comment]
Thank you for your response.
