### ISSUE TITLE
Binding editing content. @bind-

### ISSUE THREAD

**Issue by toklive** [Blazored/TextEditor#20]
Is there a way to bind the value in the editor ? (looking for two-way binding using @bind-)

**Comment by ADefWebserver** [comment]
No we don't have this on purpose. 
The JavaScript editor is handling the display and input.  It is not happening in Blazor or C#.
Therefore, the API is designed to communicate with the JavaScript layer only on initial display and saving.
True binding is not in the design.

**Comment by toklive** [comment]
Got it. Thanks for your prompt response.
