### ISSUE TITLE
Clear links from paste

### ISSUE THREAD

**Issue by aljaz00** [Blazored/TextEditor#24]
Is there any way to clear links from pasted HTML?

Thanks for your answer!

**Comment by ADefWebserver** [comment]
See:
https://github.com/quilljs/quill/issues/1821

**Comment by aljaz00** [comment]
I used regular expressions to remove links on save action.

Here is the solution:
`QuillHTMLContent = Regex.Replace(QuillHTMLContent, @"<a\b[^>]+>([^<]*(?:(?!</a)<[^<]*)*)</a>", "$1");`

Thanks for the help anyway!
