### ISSUE TITLE
How to load data on page load

### ISSUE THREAD

**Issue by imprathamesh** [Blazored/TextEditor#25]
i retreive data from database 
and want to load on pageload  - OnInitializedAsyce() of blazor webassembly razor page. 

I tried to add await QuillHtml.LoadHTMLContent(@"<h1>HELLO</h1>") 

but its not showing on page load in TextEditor. What is the exact issue?

**Comment by ADefWebserver** [comment]
Please look at the examples here:
https://github.com/Blazored/TextEditor/blob/main/samples/BlazorClientSide/Pages/Index.razor
