### ISSUE TITLE
it#s not working for .NET5

### ISSUE THREAD

**Issue by jude1003** [Blazored/TextEditor#28]
Hai i just updated to .net 5 an it's not working anymore

**Comment by jude1003** [comment]
![image](https://user-images.githubusercontent.com/74536184/99542413-54e2cf80-29b2-11eb-85bc-8aecdf8729c5.png)

**Comment by ADefWebserver** [comment]
You can _consume_ the control in a .Net 5 project.
Do not try to upgrade the control its self to .Net 5

**Comment by jude1003** [comment]
hallo, i did not update the control to .net 5. I am using the nuget packet

**Comment by ADefWebserver** [comment]
I just created a .Net 5 server project and it worked fine?

![image](https://user-images.githubusercontent.com/1857799/99561704-1af6d680-297c-11eb-96ad-a5f8764c0f08.png)

**Comment by ADefWebserver** [comment]
Here is my sample project: 
[BlazorSeverTextEditor.zip](https://github.com/Blazored/TextEditor/files/5561649/BlazorSeverTextEditor.zip)

**Comment by ADefWebserver** [comment]
Here is a Blazor .Net 5 WebAssembly version

[BlazorClientTextEditor.zip](https://github.com/Blazored/TextEditor/files/5561930/BlazorClientTextEditor.zip)

![image](https://user-images.githubusercontent.com/1857799/99571190-d07b5700-2987-11eb-8f7f-1b9ab5e6699d.png)

**Comment by jude1003** [comment]
Hallo, Thanks for your help. I have two machines, on one is working without any problem but on other not... i can't find the solution.

**Comment by ADefWebserver** [comment]
@jude1003 On the machine that it does not work on. Can you go to:
https://cdn.quilljs.com/1.3.6/quill.js
If you cannot, that is the problem.
