### ISSUE TITLE
Problems with <div> Tags?

### ISSUE THREAD

**Issue by datekk** [Blazored/TextEditor#31]
Hi, I like to use your Editor in my Project.. But the Editor should have a problem with div-Tags.

Everytime when the quillcontent contains a div tag, I get the error "Uncaugth TypeError: Cannot read property 'emit' of undefined at Scroll.update".

Can you help fixing it?

**Comment by ADefWebserver** [comment]
This is just a wrapper around the JavaScript component Quill.JS https://quilljs.com/
So it can only do what Quill can do.
Perhaps you can create a [Quill Custom Module](https://quilljs.com/guides/building-a-custom-module/).
