### ISSUE TITLE
Change event

### ISSUE THREAD

**Issue by bobonic** [Blazored/TextEditor#33]
How can we bind a model to the editor that sets the html value to the model?

**Comment by ADefWebserver** [comment]
Because the underlying Quill.js is actually making any changes, you would have to detect that change using custom JavaScript.
See: https://quilljs.com/0.20/docs/events/

**Comment by ThatFlashCat** [comment]
This fork may be helpful: https://github.com/Vixys/TextEditor

**Comment by ADefWebserver** [comment]
@ThatFlashCat - Thanks for that link. That is very helpful.

I looked at that code, and my concern is that there is a lot of 'traffic' when a person is using the Rich Text control. With Server Side Blazor apps, if you had other things on the page, you could have a significant performance penalty. This is why I did not put it in the **Blazored Text Editor**. 

When you have a large document in the **Blazored Text Editor** you will notice there is a 'slowness' in your web browser even without adding this additional feature.

**Comment by ThatFlashCat** [comment]
@ADefWebserver Perhaps it could be added as an option with a warning about possible performance issues? Up until now I was using a custom CKEditor component that updated the associated model whenever the user typed. The overhead wasn't bad for short documents (I limited to 6000 characters).

**Comment by ADefWebserver** [comment]
@ThatFlashCat - I seriously considered that, but I would not put in a feature that I myself would never recommend (or use). Every feature added to this component comes at a cost to reliability and stability. 

- You only *need* the contents of the editor when the user clicks the Save button.
- Any other events need to be handled in JavaScript. Marshalling the events back to C#, while the users is editing, is not something I feel is worth the performance penalty.

**Comment by ThatFlashCat** [comment]
In my case, I have an autosave timer that is triggered when the content is changed. Otherwise, getting it manually before submitting would work.

**Comment by ADefWebserver** [comment]
@ThatFlashCat - Yes, that makes sense as a valid reason for wanting the contents before a manual Save. 
May I suggest a JavaScript timed function that calls a server side API that periodically saves the data?

**Comment by ThatFlashCat** [comment]
@ADefWebserver That is a possible alternative, yes, although at this time I have not had performance issues with the text changed event.

**Comment by suspense304** [comment]
> This fork may be helpful: https://github.com/Vixys/TextEditor

How do I import that into my project? I don't seem to be able to get it to work

**Comment by ClumsyPenguin** [comment]
Could someone provide a Example on how to set this up with the Text Change event from Quilljs itself, i am having a hard time on this eventlistener

**Comment by ADefWebserver** [comment]
You have to alter the code in [Blazored-BlazorQuill.js](https://github.com/Blazored/TextEditor/blob/main/src/Blazored.TextEditor/wwwroot/Blazored-BlazorQuill.js).

See the **insertQuillImage** method in **Blazored-BlazorQuill.js**.

**Comment by ADefWebserver** [comment]
> Could you please provide a more in-depth example on TextChange it fails to bind on it.

Sorry Quill is a huge library, with a lot of versions, and I am not an expert on it. 
Thank you for your understanding.

**Comment by ClumsyPenguin** [comment]
This snippet works with the latest version of quill!

```ts
static createQuill(quillElement, toolBar, readOnly, placeholder, theme, debugLevel) {
        Quill.register('modules/blotFormatter', QuillBlotFormatter);
        var quill = new Quill(quillElement, {
            modules: {
                toolbar: toolBar,
                blotFormatter: {}
            },
            placeholder: placeholder,
            readOnly: readOnly,
            theme: theme,
            debug: debugLevel
        });

        quill.on('text-change', function (delta, oldDelta, source) {
            if (source == 'user') {
                console.log("A user action triggered this change.");
            }
        });

    }
```
