### ISSUE TITLE
When activating an effect and typing, after the first letter it jumps back

### ISSUE THREAD

**Issue by Sahara150** [Blazored/TextEditor#35]
So to reproduce, you simply need to insert a basic editor. 
When you click e.g. on bold before typing, it obviously colors bold as blue. 
But after you typed the first letter, your cursor starts in front of it again. Resulting in weird words like 

uler instead of rule

I appended an example, where you can see, that I activated bold and italic, then typed an "I" and without doing anything the cursor jumped in front of it. 
![example](https://user-images.githubusercontent.com/74471023/105188067-c9adc380-5b33-11eb-92d7-052e770bda54.png)

**Comment by ADefWebserver** [comment]
This may be a bug in the underlying Quill editor.
The component is just a wrapper around Quill.js
You can pull down the source of this component, and replace the contents of this file:

https://github.com/Blazored/TextEditor/blob/main/src/Blazored.TextEditor/wwwroot/Blazored-BlazorQuill.js

To see if that resolves your issue.

Thank You
