### ISSUE TITLE
Adding a method returning the Quill-Object for customizable handlers

### ISSUE THREAD

**Issue by Sahara150** [Blazored/TextEditor#36]
Hey, 
I was wondering, if it would be possible to return the Quill object when creating it and saving it in a reference in your editor? 

That would bring the possibility to write extensions, that get the object handed over, which add customizable handlers for own formatting buttons you might wanna create.

**Comment by ADefWebserver** [comment]
Sorry no.
For stability, it is important that this component be a simple "wrapper' around the underlying Quill.js library.
Yes, this limits the functionality.
