### ISSUE TITLE
Not able to create control dynamically 

### ISSUE THREAD

**Issue by vvsms** [Blazored/TextEditor#38]
Hello,
I'm trying to give users the option to add contact dymically,
they can click on a button and the controls will be created.
but when I'm trying to use the control dynamically the data is not getting read.
regards,
vvsm

**Comment by ADefWebserver** [comment]
This control is not designed to support that scenario. You will have to implement that sort of code in JavaScript.

**Comment by vvsms** [comment]
thank you
