### ISSUE TITLE
Browser developer console overcrowded by info messages

### ISSUE THREAD

**Issue by adopilot** [Blazored/TextEditor#4]
First , thanks a lot on all efort, it is great to have such component in blazor.
Little annoying thing for us developer is that on every single click inside control, developer console returning info message.
![image](https://user-images.githubusercontent.com/4448913/70810303-d1912500-1dc3-11ea-85ec-6b17ae5f58b2.png)

When I open jquill.js as 1987 line there is code

` (_console = console)[method].apply(_console, args); // eslint-disable-line no-console`

Can we increase debug level

**Comment by ADefWebserver** [comment]
There is a `DebugLevel` property you can set to 'turn this down' (for example change it to just `error`):

> DebugLevel (Optional - Default: info) - Determines the level of debug information returned to the web browser console window. Options are error, warn, log, or info.

So you can use:

`<BlazoredTextEditor @ref="@QuillReadOnly" DebugLevel="error">`

**Comment by BenMakesGames** [comment]
is it possible to set this globally somewhere? it might be nice for devel, but isn't wanted for deployment.

**Comment by ADefWebserver** [comment]
This control only supports settings on the "component level" as demonstrated in my earlier comment. Thanks
