### ISSUE TITLE
Question about default placeholder

### ISSUE THREAD

**Issue by kdvis** [Blazored/TextEditor#41]
Am I able to change the default placeholder from "compose an epic..." to something else? If so, where can I make that change?

**Comment by ADefWebserver** [comment]
Where do you see that? [Quill.js usually has that](https://quilljs.com/docs/configuration/#options), but, we don't have that in our project.

**Comment by kdvis** [comment]
Oh, you are right, this is a quill.js thing. Thank you for steering me in the right direction!
