### ISSUE TITLE
Feature Request: Catch and Rethrow JS Interop Exceptions as BlazorTextEditorException

### ISSUE THREAD

**Issue by pha3z** [Blazored/TextEditor#49]
Because Visual Studio makes it difficult to suppress specific exceptions (the only thing you can do easily is suppress based on Exception Type), it would be greatly helpful if exceptions thrown from BlazorTextEditor calls would catch JS Interop exceptions and rethrow a new exception as type 'BlazorTextEditorException'.

This would make it very easy to tell Visual Studio Debugger to ignore exceptions of type BlazorTextEditorException.

**Comment by ADefWebserver** [comment]
I am unsure why this would be necessary. The stack trace would reveal the source of the exception, correct?

**Comment by pha3z** [comment]
The point is to be able to tell the Debugger to continue instead of breaking when the exception occurs.  I wrote a try catch block to handle the exception, so I don't need to break and trace anything.  I don't need the debugger to break just because a JSInteropException occurs in BlazorTextEditor.  However, I still would want a break if some other JSInteropException occurred elsewhere in my application. 

Visual Studio will only allow you to control halting based on Type of exception. This is the reason why its important to create specific exceptions in libraries -- so that you get control in the debugger about when to break and when not to.

**Comment by pha3z** [comment]
Here is some discussion on SO talking about how this is a systemic problem in Visual Studio that needs to be fixed.  There is a horrible impractical workaround that relies on moving code to an external library.

In lieu of a proper solution, the most sensible solution is to have proper named Exceptions so you can ignore the relevant Exception type.

**Comment by pha3z** [comment]
https://stackoverflow.com/questions/1420390/dont-stop-debugger-at-that-exception-when-its-thrown-and-caught?noredirect=1&lq=1

**Comment by ADefWebserver** [comment]
I looked over the discussion, and I thought a lot about your request. However, this component is used by thousands of applications. I can't put in something unusual like this. Sorry.

**Comment by pha3z** [comment]
Maybe we're not understanding each other.

Are you saying you think its unusual to write a try-catch block to catch a JsInterop exception and rethrow as a BlazorEditorException???

Such a change is likely to have zero impact on 99% of applications.  The only applications that would be impacted would be ones where someone wrote code that catches the JsInteropException and makes some evaluation based on its particular type. Most users who write code like that should already be well aware of the brittleness of such code and would probably expect something like that to break.  Besides that, you'd be giving them more flexibility if you gave a more specific exception.

This is not at all remotely strange. Its good library design.

**Comment by ADefWebserver** [comment]
*any* change can have *consequences* and must be carefully considered. With this component I only fix any bugs and maintain a stable component.

**Comment by pha3z** [comment]
This is arguably a bug.  Because you're not catching exceptions, you're allowing JSInterop exceptions to bubble up to consumer code.  This makes it impossible for debugger to distinguish between handling exceptions within BlazorTextEditor vs exceptions originating from some other part of the application.

With certainty, it makes using the library unnecessarily difficult (as is demonstrated in my case...  every time blazor editor throws an exception, I'm forced to hop through all the exceptions to keep the debugger running).  And arguably its a faulty library design or even a bug. I wouldn't consider this to be excepted behavior.

**Comment by pha3z** [comment]
You still feel this is not a bug?

**Comment by ADefWebserver** [comment]
@pha3z - At this time I do not consider this a bug. You are free to Fork this project and make the changes you desire (please give your project a new name). Thanks!
