### ISSUE TITLE
Convert quill delta to HTML in Blazor/inline css styling

### ISSUE THREAD

**Issue by AnDsoz** [Blazored/TextEditor#50]
Hi,

Is there a way to convert to do the below  in a Blazor server side application?

Convert Quill delta to the equivalent HTML with **inline styling**  and not the quill classes so that the content can be recognized by google or any other page using it which do not recognize the quill classes?

Right now the content i edit in quilll editor and save into my database is faulty becuase the indent,font name etc are not recognized by google.

**Comment by ADefWebserver** [comment]
Sorry no.
