### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by Mark-Phillipson** [Blazored/TextEditor#51]
Is it possible to, perhaps using JavaScript interop, to focus the text editor when the page loads?

The elements does not appear to have an ID.

**Comment by ADefWebserver** [comment]
I will try to add an id to the div in the next few weeks when I have time.

I considered adding a "focus", but creating 'handlers' has a significant performance penalty. Also, people could have multiple instances of this control on a page so I would not know which instance to provide focus to.

Thanks
