### ISSUE TITLE
how can to use that in modal ?

### ISSUE THREAD

**Issue by andreyshiryaev** [Blazored/TextEditor#52]
Good day! 

Could you please show an example for using BlazoredTextEditor in modal popup

I tried to use the next code but QuillHtml is null

`@inject IModalService ModalService

<div>
    <BlazoredTextEditor @ref="@QuillHtml">
        <ToolbarContent>
            <select class="ql-header">
                <option selected=""></option>
                <option value="1"></option>
                <option value="2"></option>
                <option value="3"></option>
                <option value="4"></option>
                <option value="5"></option>
            </select>
            <span class="ql-formats">
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
                <select class="ql-color"></select>
                <select class="ql-background"></select>
            </span>
            <span class="ql-formats">
                <button class="ql-list" value="ordered"></button>
                <button class="ql-list" value="bullet"></button>
            </span>

        </ToolbarContent>
      
    </BlazoredTextEditor>

    <button @onclick="async ()=> await ApplyAsync()" class="btn btn-primary">ApplyAsync</button>
    <button @onclick="Cancel" class="btn btn-secondary">Cancel</button>
</div>

@code {

    private BlazoredTextEditor QuillHtml;

    [Parameter]
    public string Text { get; set; }

    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }

    protected override async Task OnInitializedAsync()
    {

        base.OnInitialized();
        await QuillHtml.LoadHTMLContent(Text); // always null

    }

    async Task ApplyAsync()
    {
        string text = await QuillHtml.GetContent();
        await BlazoredModal.Close(ModalResult.Ok(text));
    }
    void Cancel()
    {
        BlazoredModal.Cancel();
    }

}`

```


    ModalParameters modalParameters = new ModalParameters();
           
            modalParameters.Add("Text", "Text<a>");

            var confirmationModal = Modal.Show<EditHtml>("Edit", modalParameters);

            var dialogResult = await confirmationModal.Result;



```

**Comment by ADefWebserver** [comment]
This project has an example of using **BlazoredTextEditor** in a popup: https://github.com/ADefWebserver/Blazor-Blogs. Specifically see this page: https://github.com/ADefWebserver/Blazor-Blogs/blob/main/BlazorBlogsLibrary/Pages/BlogAdministration.razor

**Comment by andreyshiryaev** [comment]
> This project has an example of using **BlazoredTextEditor** in a popup: https://github.com/ADefWebserver/Blazor-Blogs. Specifically see this page: https://github.com/ADefWebserver/Blazor-Blogs/blob/main/BlazorBlogsLibrary/Pages/BlogAdministration.razor

Thank you. But I need to use Blazored.Modal

**Comment by ADefWebserver** [comment]
Sorry I have no examples.
