### ISSUE TITLE
Focus is lost when pasting large amount of text/image

### ISSUE THREAD

**Issue by barnebyte-timewarp** [Blazored/TextEditor#56]
After pasting a large body of text or image, the cursor (at the end of the document) is getting out of focus:

![image](https://user-images.githubusercontent.com/110464157/219364843-8df9adf0-c626-40b1-9d2f-a3d1d2d0e7f0.png)
![image](https://user-images.githubusercontent.com/110464157/219365092-b9b2ed02-2057-4def-b4d4-1a82278c595b.png)

**Comment by ADefWebserver** [comment]
This is by design.
