### ISSUE TITLE
Loading the latest value of the text editor

### ISSUE THREAD

**Issue by mloutsaris** [Blazored/TextEditor#57]
Hello and thanks for your TextEditor,

i have a problem in my code. I am trying to use a multiple texteditors inside a foreach. Also, i want to give the ability to my users to change the order of the text editors. 
However, when i change the order i cannot change the editorcontent in the UI but the values are saved in the correct ordering. 

My code snippets are the following: 
 @foreach (var body in Law.LawBody)
                    {
` <BlazoredTextEditor @ref="@(bodyEditors[body.BodyId])">
                                            <ToolbarContent>
                                                <select class="ql-header">
                                                    <option selected=""></option>
                                                    <option value="1"></option>
                                                    <option value="2"></option>
                                                    <option value="3"></option>
                                                    <option value="4"></option>
                                                    <option value="5"></option>
                                                </select>
                                                <span class="ql-formats">
                                                    <button class="ql-bold"></button>
                                                    <button class="ql-italic"></button>
                                                    <button class="ql-underline"></button>
                                                    <button class="ql-strike"></button>
                                                </span>
                                                <span class="ql-formats">
                                                    <select class="ql-color"></select>
                                                    <select class="ql-background"></select>
                                                </span>
                                                <span class="ql-formats">
                                                    <button class="ql-list" value="ordered"></button>
                                                    <button class="ql-list" value="bullet"></button>
                                                </span>
                                                <span class="ql-formats">
                                                    <button class="ql-link"></button>
                                                </span>
                                                <span class="ql-formats">
                                                    <button class="ql-image"></button>
                                                </span>
                                            </ToolbarContent>
                                            <EditorContent>
                                                @body.BodyValue
                                            </EditorContent>
                                        </BlazoredTextEditor>}`
and the function that adds texteditors: 
` Dictionary<string, int> bodyIndexes = new Dictionary<string, int>();
    int indexnumber = 0;
    private void AddBody()
    {
        indexnumber++;
        // Law.LawBody.Add(new LawBodyModel());
        LawBodyModel newBody = new LawBodyModel();
        newBody.BodyId = GenerateRandomId(); // Generate a random ID
        Law.LawBody.Add(newBody);
        bodyIndexes[newBody.BodyId] = indexnumber;
    }`
the movebodyup function
`Dictionary<string, BlazoredTextEditor> bodyEditors = new Dictionary<string, BlazoredTextEditor>();
string Content;
    private async void MoveBodyUp(LawBodyModel body)
    {
        int index = Law.LawBody.IndexOf(body);
        if (index > 0)
        {
            Law.LawBody.Remove(body);
            Law.LawBody.Insert(index - 1, body);

        }
        bodyIndexes[body.BodyId] = index - 1;

        // Update the position of the associated BlazoredTextEditor instance
        var editor = bodyEditors[body.BodyId];
        bodyEditors.Remove(body.BodyId);
        bodyEditors.Add(body.BodyId, editor);
        Content = await this.bodyEditors[body.BodyId].GetContent();
        await this.bodyEditors[body.BodyId].LoadContent(Content);
        StateHasChanged();
    }`

and on submission of the form i am doing the following 

`foreach (var body in Law.LawBody)
        {
            var content = await bodyEditors[body.BodyId].GetHTML();
            body.BodyValue = content;
            foreach (var correlation in body.LawCorrelations)
            {
                var corcontent = await correlationEditors[correlation.CorrelationTargetLDNumber + correlation.CorrelationTargetLDPartNumber].GetHTML();
                correlation.CorrelationTargetLDText = corcontent;
            }
        }`

can you please help me ? thank you again for your time

**Comment by ADefWebserver** [comment]
I'm sorry but the control will not work when used that way.

**Comment by ADefWebserver** [comment]
@mloutsaris - More information regarding this. It is possible to have a control that can have multiple instances on a page and still allow programmatic input and output with the C# code. However, you would have to marshal a massive about of data and handlers from JavaScript to the backend C# code. This would have a huge performance penalty. There are controls for Blazer that allow this.
