### ISSUE TITLE
Table Support

### ISSUE THREAD

**Issue by Tastanium** [Blazored/TextEditor#6]
is there any table support?

**Comment by ADefWebserver** [comment]
You can implement that using a plug-in like this:
https://github.com/quilljs/quill/issues/1700

The reason it is not built-in, is that it requires extra scripts and everyone may not want it.

**Comment by Tastanium** [comment]
thats sad :)

**Comment by unkn0wn-developer** [comment]
It would be great if there was an official script or endorsement/official help/maintenance for one of the third-party scripts.
 For example, this one: https://github.com/soccerloway/quill-better-table

There are bunch of open issues for this github project even though it works.
