### ISSUE TITLE
Version number on DLL file is wrong

### ISSUE THREAD

**Issue by trickshot2012** [Blazored/TextEditor#61]
Thank you for your work on Blazored.Texteditor !

**Describe the bug**
Not really a bug but quite irritating when you check version numbers on DLL file:
I just updated my Blazored.Texteditor NuGet Package from Version 1.0.8 to 1.1.0
The Product Version number of the DLL file is now **1.0.0**
The File Version number is now **1.0.0.0**

**To Reproduce**
Check properties of DLL file

**Expected behavior**
Expected Product Version 1.1.0
Expected File Version 1.1.0.0

**Screenshots**

Version 1.0.8
![grafik](https://github.com/Blazored/TextEditor/assets/40659134/2b4982b5-588f-4ddd-b944-29714af6813c)

Version 1.1.0
![grafik](https://github.com/Blazored/TextEditor/assets/40659134/27f1580c-98c9-47c0-8570-7b7ba5c90808)

**Comment by ADefWebserver** [comment]
I will consider a PR from the community for this. Thank you
