### ISSUE TITLE
ReadOnly does not work

### ISSUE THREAD

**Issue by Senso4sLab** [Blazored/TextEditor#62]
when the component is loaded the toggling readOnly mode does not work at all!

**Comment by ADefWebserver** [comment]
Please download the code, right-click on the BlazorServerSide project and select Set as Startup Project. Hit F5 to run it. You can click on "Read Only Content" and if you try to type nothing will happen. Now click once on the "Toggle Editor button. Now if you click on "Read Only Content" and try to type something it will allow you to edit that content.
