### ISSUE TITLE
Placeholder not displaying correctly in Editor content

### ISSUE THREAD

**Issue by anotherRedbeard** [Blazored/TextEditor#64]
**Describe the bug**
Placeholder not showing up in the Editor field as expected

**To Reproduce**
1. Create a new BlazoredTextEditor control and set a Placeholder value
2. Run the app and see if placeholder value is in the editor

**Expected behavior**
Placeholder value should be in the editor.

**Screenshots**
Here is the result:
<img width="1677" alt="image" src="https://github.com/Blazored/TextEditor/assets/34103220/dedb9ab2-f858-403e-8206-0692baf66e2a">

If I remove the <p> </p> in the running session via Chrome browser tools it shows up as expected:
<img width="1669" alt="image" src="https://github.com/Blazored/TextEditor/assets/34103220/59c3301e-1565-4ef1-85ec-bf2f6f5be3ff">

Happy to discuss further if I'm doing something that is causing this.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
Here is my razor:

    <BlazoredTextEditor @ref="@QuillHtml" Placeholder="@Placeholder">
        <ToolbarContent>
            @((MarkupString) toolbar)
        </ToolbarContent>
        <EditorContent>
            @((MarkupString)@RichText)
        </EditorContent>
    </BlazoredTextEditor>

**Comment by ADefWebserver** [comment]
Unless I am mistaken this is controlled by the underlying Quill.js library. Please let me know if you think I am wrong.
If it is the underlying Quill.js library, we are kinda stuck because this Blazor control is just a 'wrapper' around that JavaScript library.

**Comment by anotherRedbeard** [comment]
More details....
When I use the following syntax it works as expected

`<BlazoredTextEditor @ref="@QuillHtml" Placeholder="@Placeholder">
        <ToolbarContent>
            @((MarkupString) toolbar)
        </ToolbarContent>
        <EditorContent>@RichText</EditorContent>
    </BlazoredTextEditor>`

**Comment by ADefWebserver** [comment]
@anotherRedbeard - Thank you for figuring that out. We can close this issue, correct?

**Comment by anotherRedbeard** [comment]
@ADefWebserver  - I'm trying to dig a little deeper, but I'm not sure where the issue is coming from.  My initial thought was the code might be able to be changed to see if the value was null or whitespace and it would render the Placeholder.  I've tried several other things to make it work without any success.

**Comment by ADefWebserver** [comment]
@anotherRedbeard - So far I don't see anything this control can change. Even the movement of `(MarkupString)` in your example is a _.Net thing_ not really the **BlazoredTextEditor**.

**Comment by anotherRedbeard** [comment]
@ADefWebserver - I didn't see anything either.  It's just odd that if you implement the sample that it doesn't show the Placeholder if you pass in an empty string to the body.  For example I just tried this pulled straight from the docs and it renders a space in the EditorContent:

```
<h3>Basic Example</h3>
<BlazoredTextEditor
    @ref="@richEditor">
    <ToolbarContent>
        @((MarkupString) toolbar)
    </ToolbarContent>
    <EditorContent>
        @((MarkupString) body)
    </EditorContent>
</BlazoredTextEditor>

@code
{
    BlazoredTextEditor richEditor = default!;
    string toolbar = """"...markup here..."""";
    string body = """"...markup here..."""";

    protected override void OnInitialized()
    {
        toolbar = """"
            <select class="ql-header">
                <option selected=""></option>
                <option value="1"></option>
                <option value="2"></option>
                <option value="3"></option>
                <option value="4"></option>
                <option value="5"></option>
            </select>
            <span class="ql-formats">
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
                <select class="ql-color"></select>
                <select class="ql-background"></select>
            </span>
            <span class="ql-formats">
                <button class="ql-list" value="ordered"></button>
                <button class="ql-list" value="bullet"></button>
            </span>
            <span class="ql-formats">
                <button class="ql-link"></button>
            </span>
            """";

        body = "";
    }
}
```

**Comment by anotherRedbeard** [comment]
I found a 'workaround' that will work for now.

```
if (string.IsNullOrWhiteSpace(body))
        {
            body = """"<p></p>""""; // empty paragraph
        }
```

For whatever reason it doesn't like there to be an empty string in there so you can just set it to an empty paragraph.  This isn't terrible given that when you call the `.GetHTML()` on the quill control when it's empty you get `<p><br></p>`

**Comment by ADefWebserver** [comment]
@anotherRedbeard - If someone using this control did not want that we would be forcing this on them, correct? For the developers who want this, using your previous work around seems the best solution, correct?

**Comment by anotherRedbeard** [comment]
@ADefWebserver - Yeah I agree this is not the solution, but can be used to workaround it.  I'll close the issue.
