### ISSUE TITLE
[Bug] If added an image you cant load the content to a variable

### ISSUE THREAD

**Issue by Moritz-Deiaco** [Blazored/TextEditor#68]
**Describe the bug**
if i try to load the editor content to a variable, while an image is in the editor, the page goes to "Attempting to reconnect to the server"

**To Reproduce**
1. Add an image to the editor
2. (i added a button to load the html to a variable, like in the docs)
3. then it says attempting to reconnect to the server

**Expected behavior**
It should load to the variable

**Comment by ADefWebserver** [comment]
This is a limitation of the blazor javascript interop. You can load a reference to an image (using an HTML image tag), but, if you put the actual contents of the image into the editor (the byte contents), it is too big and crashes when you try to marshal that data back to Blazor.

**Comment by Moritz-Deiaco** [comment]
Thank you... It works now!
