### ISSUE TITLE
Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'removeChild') [Bug]

### ISSUE THREAD

**Issue by Meoqan** [Blazored/TextEditor#71]
**Describe the bug**
If the Quill is used in nested subelements and attempts to use GetHTML it will throw an error.

**To Reproduce**
1. Use Quill in a sub-element: EditorPage > SubFragment(List) > Quill Editor
2. When saving, the content is read out with GetHTML (async)
3. an error appears in the console: `Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'removeChild')`

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by ADefWebserver** [comment]
The reason I don't consider this a bug is that the component is not able to reach the required HTML element on the page, because of the nesting. This is definitely a _limitation_ in how the component can be used, but, not a _bug_.

**Comment by Meoqan** [comment]
The editor works even if it is used nested.
I found the cause of the problem:

```
@if (!hide)
{
  <BlazoredTextEditor @ref="QuillNative" Placeholder="">
      <EditorContent>
          @((MarkupString)@NewNewsArticleItem.Text) <!-- gets updated, when the variable is set, but fails to update -->
      </EditorContent>
  </BlazoredTextEditor>
}
```

```
string txt = await QuillNative.GetHTML();  // works fine
hide = !hide;
NewNewsArticleItem.Text = txt; // causes error
```
The problem can be solved by simply hiding the editor immediately after the HTML has been fetched and before it is then written to the variable.
