### ISSUE TITLE
[Bug] [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. 

### ISSUE THREAD

**Issue by Markus243** [Blazored/TextEditor#72]
**Describe the bug**
Using the cdn's 1.3.7 as per the documentation I encounter: [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**To Reproduce**
1. Follow the documentation for setup
2. Browser warns: [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
I tried updating to later versions of QuillJs >2.00 but this seems to break compatibility with blazored texteditor. Any help/solutions or workarounds would be greatly appreciated.

**Comment by ADefWebserver** [comment]
I am not sure if this component should be upgraded. Perhaps a new component should be created instead. 
However, what issues did you see when you updated to Quill 2.00?

**Comment by markushaslinger** [comment]
> However, what issues did you see when you updated to Quill 2.00?

A simple replacement of the js & css files to current quill 2.0.1 gave me the following error:

```
Cannot read properties of null (reading '__quill')
    at Object.loadQuillHTMLContent (http://localhost:5204/_content/Blazored.TextEditor/Blazored-BlazorQuill.js:40:33)
```

**Comment by ADefWebserver** [comment]
@markushaslinger A new Blazor component would need to be created from scratch to work with Quill 2.0
