### ISSUE TITLE
Quill JS 2.0

### ISSUE THREAD

**Issue by dennisrahmen** [Blazored/TextEditor#73]
I was just checking on Quill JS's Homepage and saw that they released a new Version 2.0 that fixes many bugs the old version had.

Since the last release is older I would like to ask if it is possible to update this library to use the new Quill JS 2.0 Version.
Here is the announcement:
https://slab.com/blog/announcing-quill-2-0/

**Comment by ADefWebserver** [comment]
I will consider a PR that is a drop-in replacement. Meaning no breaking chnages. However, I do not believe it is possible, so I am closing this as it is not planned.

**Comment by S-Luiten** [comment]
I don't see anything in the migration guide that would be a breaking change, so I tried updating to v2.0.3. Only issue I ran into was that `quillElement.__quill` no longer seems to work, for which I made a solution using `IJSObjectReference`. This type requires .NET 5.0 or later, and since this library is targeting .NET standard 2.0, that would be a breaking change.

**Comment by ADefWebserver** [comment]
> This type requires .NET 5.0 or later, and since this library is targeting .NET standard 2.0, that would be a breaking change.

Thank you for hunting this down and identifying the issue. **I would rather have people use another package** than create a breaking change in this one.

**Comment by S-Luiten** [comment]
In quill.js v1.3.6, the quill object reference is automatically added to the container element, but this was removed in v2.x
I think it should work if you add it back manually in `QuillFunctions.createQuill`:
```js
quillElement.__quill = new Quill(quillElement, options);
```

With this workaround the target framework doesn't need to be updated, so there's no breaking change.

**Comment by ADefWebserver** [comment]
@S-Luiten - I will consider a PR for this. Thanks
