### ISSUE TITLE
[Feature Request] bind-Value support

### ISSUE THREAD

**Issue by maot01** [Blazored/TextEditor#74]
**Is your feature request related to a problem? Please describe.**
When trying to save html/text in a modal/form, you have to use custom validation right now since the editor does not support bind-value like for example text-field components.

**Describe the solution you'd like**
If we could set bind-value on either the BlazorTextEditor or the EditorContent, which would work together with DataAnnotations, such as if lets say the text is Required, length etc.

**Describe alternatives you've considered**
Right now the only way around this is to implement your own custom validation without DataAnnotations such as Required, and check content with the await this.QuillHtml.GetHTML() method.

**Additional context**

Example of what I mean (in either place).

![image](https://github.com/user-attachments/assets/085b86f7-018b-4bac-b791-12cb7c55737c)

**Comment by ADefWebserver** [comment]
Because this control is Javascript based the bind just causes horrible performance. Radzen.com does have a HTML control that will do what you need
