### ISSUE TITLE
[Feature Request] Add overloads with CancellationToken parameter to async methods.

### ISSUE THREAD

**Issue by S-Luiten** [Blazored/TextEditor#76]
**Is your feature request related to a problem? Please describe.**
I'd like to add a timeout to `GetHTML` using a `CancellationTokenSource`. However, this method does not take a `CancellationToken`.

**Describe the solution you'd like**
An overload for `GetHTML` and other async methods which takes a cancellationToken parameter and passes it to `jsRuntime.InvokeAsync`.

**Describe alternatives you've considered**
Due to requiring a reference to the private field `QuillElement`, I'm currently forced to use reflection to get this reference, and manually call `jsRuntime.InvokeAsync`.

**Comment by ADefWebserver** [comment]
I will consider a PR for this.
