### ISSUE TITLE
[Question] Code Block Settings

### ISSUE THREAD

**Issue by AlexHedley** [Blazored/TextEditor#79]
When including the `code block` toolbar item `</>` is there a way to turn on the syntax highlighting?

```html
<span class="ql-formats">
    <button class="ql-code-block"></button>
</span>
```

`modules: {  syntax: true }`

- https://quilljs.com/docs/modules/syntax

```html
<script>
const quill = new Quill('#editor', {
  modules: {
    syntax: true,              // Include syntax module
    toolbar: [['code-block']]  // Include button in toolbar
  },
  theme: 'snow'
});
...
</script>
```

**Comment by ADefWebserver** [comment]
I would consider a PR for this if it can be done without making a breaking change.

**Comment by AlexHedley** [comment]
@ADefWebserver I've created a new PR https://github.com/Blazored/TextEditor/pull/80 to add this functionality. The default is `false` so shouldn't break existing versions. Have added examples of both in the samples.

**Comment by ADefWebserver** [comment]
Merged. Thanks!
