### ISSUE TITLE
What about PDF Editor?

### ISSUE THREAD

**Issue by Oleg26Dev** [Blazored/TextEditor#8]
I have a project where pdf files are uploaded to database.
I'd like to do: user clicks button <View> and view the pdf from the database.
Also, edit and save the pdf back. 
Is it possible to do it using the TextEditor?

**Comment by ADefWebserver** [comment]
The text editor only handles two formats. Its native "Delta" format and "HTML". You would have to use an additional component to convert your PDF to one of those formats. See: https://stackoverflow.com/questions/55135981/how-do-i-upload-filespdf-doc-etc-via-quill-js-rich-text-editor
